# Generated by Django 4.2.20 on 2025-04-21 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='gpt_review',
            field=models.TextField(blank=True, null=True),
        ),
    ]
