# Generated by Django 4.2.20 on 2025-04-21 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_feedback_gpt_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='needs_attention',
            field=models.BooleanField(default=False),
        ),
    ]
